using System.Reflection;
using System.Reflection.Emit;
using System.Security.Cryptography;
using System.Text;

internal static class Program
{
    private const BindingFlags DeclaredPublic = BindingFlags.Public | BindingFlags.Instance |
        BindingFlags.Static | BindingFlags.DeclaredOnly;
    private const BindingFlags DeclaredAccessible = BindingFlags.Public | BindingFlags.NonPublic |
        BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
    private static readonly NullabilityInfoContext Nullability = new();
    private static readonly Dictionary<short, OpCode> OpCodesByValue = BuildOpCodes();

    private sealed record BodyCandidate(
        string Assembly,
        string Owner,
        string Member,
        string Signature,
        string Finding)
    {
        internal string Key => string.Join('\0', Assembly, Owner, Member, Signature, Finding);
        internal string Tsv => string.Join('\t', new[]
        {
            Clean(Assembly), Clean(Owner), Clean(Member), Clean(Signature), Clean(Finding)
        });
    }

    private static int Main(string[] args)
    {
        if (args.Length < 3 || args[0] is not ("generate" or "audit" or "audit-accessible"))
        {
            Console.Error.WriteLine(
                "Usage: PublicContractCompiler generate <output.cs> <strong-keys.tsv> <assembly> [<assembly> ...]\n" +
                "   or: PublicContractCompiler audit <output.tsv> <assembly> [<assembly> ...]\n" +
                "   or: PublicContractCompiler audit-accessible <output.tsv> <assembly> [<assembly> ...]");
            return 2;
        }

        var output = Path.GetFullPath(args[1]);
        var assemblyOffset = args[0] == "generate" ? 3 : 2;
        if (args.Length <= assemblyOffset) throw new ArgumentException("At least one assembly is required.");
        var assemblyPaths = args.Skip(assemblyOffset).Select(Path.GetFullPath)
            .Order(StringComparer.Ordinal).ToArray();
        foreach (var path in assemblyPaths)
            if (!File.Exists(path)) throw new FileNotFoundException("Package assembly is missing", path);

        var directories = assemblyPaths.Select(Path.GetDirectoryName).OfType<string>()
            .Distinct(StringComparer.Ordinal).ToArray();
        AppDomain.CurrentDomain.AssemblyResolve += (_, eventArgs) =>
        {
            var name = new AssemblyName(eventArgs.Name).Name + ".dll";
            var match = directories.Select(directory => Path.Combine(directory, name))
                .FirstOrDefault(File.Exists);
            return match is null ? null : Assembly.LoadFrom(match);
        };

        var assemblies = assemblyPaths.Select(Assembly.LoadFrom).ToArray();
        Directory.CreateDirectory(Path.GetDirectoryName(output)!);
        if (args[0] == "generate") Generate(output, Path.GetFullPath(args[2]), assemblies, assemblyPaths);
        else if (args[0] == "audit") Audit(output, assemblies);
        else AuditAccessible(output, assemblies);
        return 0;
    }

    private static void Generate(
        string output,
        string strongKeysFile,
        Assembly[] assemblies,
        string[] assemblyPaths)
    {
        var strongKeys = File.ReadAllLines(strongKeysFile)
            .Where(line => !string.IsNullOrWhiteSpace(line) && !line.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);
        if (strongKeys.Count == 0) throw new InvalidDataException("Strong contract key set is empty.");
        var foundStrongKeys = new HashSet<string>(StringComparer.Ordinal);
        var compiledStrongKeys = new HashSet<string>(StringComparer.Ordinal);
        var uncompiledStrongSignatures = new List<string>();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.IO;");
        source.AppendLine("using System.Linq;");
        source.AppendLine("using System.Security.Cryptography;");
        source.AppendLine("internal static class GeneratedPublicContractSignatures");
        source.AppendLine("{");
        source.AppendLine("    private static void Consume(object? value) { }");

        var typeReferences = new List<string>();
        var expectedRows = new List<string>();
        var referenceCount = 0;
        var generatedReferenceCount = 0;
        var runtimeOnlyCount = 0;
        foreach (var assembly in assemblies.OrderBy(item => item.GetName().Name, StringComparer.Ordinal))
        {
            foreach (var type in ExportedTypes(assembly).OrderBy(TypeName, StringComparer.Ordinal))
            {
                var openType = CSharpType(type, new Dictionary<Type, string>(), unbound: true);
                typeReferences.Add(openType);
                expectedRows.Add(Row(type));
                if (MarkStrong(type, "type", StripArity(type.Name), 0,
                               strongKeys, foundStrongKeys))
                    compiledStrongKeys.Add(StrongKey(type, "type", StripArity(type.Name), 0));
                foreach (var constructor in type.GetConstructors(DeclaredPublic)
                             .OrderBy(MethodKey, StringComparer.Ordinal))
                {
                    expectedRows.Add(Row(constructor));
                    if (!MarkStrong(constructor, "constructor", ".ctor", constructor.GetParameters().Length,
                                    strongKeys, foundStrongKeys)) { runtimeOnlyCount++; continue; }
                    if (!TryWriteExecutableReference(source, constructor, referenceCount++))
                    {
                        runtimeOnlyCount++;
                        uncompiledStrongSignatures.Add(Row(constructor));
                    }
                    else
                    {
                        generatedReferenceCount++;
                        compiledStrongKeys.Add(StrongKey(constructor, "constructor", ".ctor",
                                                         constructor.GetParameters().Length));
                    }
                }

                foreach (var property in type.GetProperties(DeclaredPublic)
                             .OrderBy(item => item.Name, StringComparer.Ordinal))
                {
                    expectedRows.Add(Row(property));
                    if (!MarkStrong(property, "property", property.Name, property.GetIndexParameters().Length,
                                    strongKeys, foundStrongKeys)) { runtimeOnlyCount++; continue; }
                    if (!TryWritePropertyReference(source, property, referenceCount++))
                    {
                        runtimeOnlyCount++;
                        uncompiledStrongSignatures.Add(Row(property));
                    }
                    else
                    {
                        generatedReferenceCount++;
                        compiledStrongKeys.Add(StrongKey(property, "property", property.Name,
                                                         property.GetIndexParameters().Length));
                    }
                }

                foreach (var field in type.GetFields(DeclaredPublic)
                             .OrderBy(item => item.Name, StringComparer.Ordinal))
                {
                    expectedRows.Add(Row(field));
                    var fieldKind = field.IsLiteral && type.IsEnum ? "enum-value" : "field";
                    if (!MarkStrong(field, fieldKind, field.Name, 0, strongKeys, foundStrongKeys))
                    { runtimeOnlyCount++; continue; }
                    if (!TryWriteFieldReference(source, field, referenceCount++))
                    {
                        runtimeOnlyCount++;
                        uncompiledStrongSignatures.Add(Row(field));
                    }
                    else
                    {
                        generatedReferenceCount++;
                        compiledStrongKeys.Add(StrongKey(field, fieldKind, field.Name, 0));
                    }
                }

                foreach (var method in type.GetMethods(DeclaredPublic)
                             .Where(item => !item.IsSpecialName)
                             .OrderBy(MethodKey, StringComparer.Ordinal))
                {
                    expectedRows.Add(Row(method));
                    if (!MarkStrong(method, "method", method.Name, method.GetParameters().Length,
                                    strongKeys, foundStrongKeys)) { runtimeOnlyCount++; continue; }
                    if (!TryWriteExecutableReference(source, method, referenceCount++))
                    {
                        runtimeOnlyCount++;
                        uncompiledStrongSignatures.Add(Row(method));
                    }
                    else
                    {
                        generatedReferenceCount++;
                        compiledStrongKeys.Add(StrongKey(method, "method", method.Name,
                                                         method.GetParameters().Length));
                    }
                }
            }
        }

        var missingStrongKeys = strongKeys.Except(foundStrongKeys, StringComparer.Ordinal).Order().ToArray();
        if (missingStrongKeys.Length != 0)
            throw new InvalidDataException("Strong contract keys are absent from package metadata: " +
                string.Join(" | ", missingStrongKeys.Take(20)));
        var uncompiledStrongKeys = strongKeys.Except(compiledStrongKeys, StringComparer.Ordinal)
            .Order().ToArray();
        if (uncompiledStrongKeys.Length != 0)
            throw new InvalidDataException("Strong contract keys lack a C# compiler reference: " +
                string.Join(" | ", uncompiledStrongKeys.Take(20)));
        if (uncompiledStrongSignatures.Count != 0)
            throw new InvalidDataException("Strong contract signatures lack a C# compiler reference: " +
                string.Join(" | ", uncompiledStrongSignatures.Take(20)));

        source.AppendLine("    private static readonly Type[] ContractTypes = new Type[]");
        source.AppendLine("    {");
        foreach (var type in typeReferences.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
            source.Append("        typeof(").Append(type).AppendLine("),");
        source.AppendLine("    };");
        source.AppendLine("    private static readonly string[] ContractRows = new string[]");
        source.AppendLine("    {");
        foreach (var row in expectedRows.Order(StringComparer.Ordinal))
            source.Append("        \"").Append(Escape(row)).AppendLine("\",");
        source.AppendLine("    };");
        source.AppendLine("    private static readonly (string Name, string Sha256)[] Assemblies = new[]");
        source.AppendLine("    {");
        foreach (var pair in assemblies.Zip(assemblyPaths)
                     .OrderBy(item => item.First.GetName().Name, StringComparer.Ordinal))
        {
            source.Append("        (\"").Append(Escape(pair.First.GetName().Name ?? "-"))
                .Append("\", \"").Append(Sha256(pair.Second)).AppendLine("\"),");
        }
        source.AppendLine("    };");
        source.AppendLine("    public static void Main()");
        source.AppendLine("    {");
        source.AppendLine("        foreach (var expected in Assemblies)");
        source.AppendLine("        {");
        source.AppendLine("            var assembly = ContractTypes.Select(type => type.Assembly).Distinct()");
        source.AppendLine("                .Single(item => string.Equals(item.GetName().Name, expected.Name, StringComparison.Ordinal));");
        source.AppendLine("            var actual = Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(assembly.Location))).ToLowerInvariant();");
        source.AppendLine("            if (!string.Equals(expected.Sha256, actual, StringComparison.Ordinal))");
        source.AppendLine("                throw new InvalidDataException($\"Loaded assembly hash differs for {expected.Name}: {actual}\");");
        source.AppendLine("        }");
        source.Append("        if (ContractRows.Length != ").Append(expectedRows.Count)
            .Append(" || ContractTypes.Length != ").Append(typeReferences.Count).AppendLine(")");
        source.AppendLine("            throw new InvalidDataException(\"Generated contract row coverage changed.\");");
        source.Append("        Console.WriteLine(\"Package-only public contract signature compilation passed: ")
            .Append(expectedRows.Count).Append(" rows, ").Append(typeReferences.Count)
            .Append(" types, ").Append(generatedReferenceCount)
            .Append(" strongly typed member references, ").Append(runtimeOnlyCount)
            .AppendLine(" metadata-only runtime references.\");");
        source.AppendLine("    }");
        source.AppendLine("}");
        File.WriteAllText(output, source.ToString(), new UTF8Encoding(false));
        Console.WriteLine(
            $"Generated public contract compiler: {expectedRows.Count} rows, {typeReferences.Count} types, " +
            $"{generatedReferenceCount} strongly typed member references, " +
            $"{runtimeOnlyCount} metadata-only runtime references.");
    }

    private static bool MarkStrong(
        MemberInfo member,
        string kind,
        string name,
        int parameterCount,
        IReadOnlySet<string> expected,
        ISet<string> found)
    {
        var key = StrongKey(member, kind, name, parameterCount);
        if (!expected.Contains(key)) return false;
        found.Add(key);
        return true;
    }

    private static string StrongKey(MemberInfo member, string kind, string name, int parameterCount)
    {
        var type = member as Type ?? member.DeclaringType!;
        return string.Join('\t', type.Assembly.GetName().Name, NormalizeOwner(TypeName(type)),
            kind, name, parameterCount);
    }

    private static string NormalizeOwner(string owner)
    {
        var result = new StringBuilder(owner.Length);
        for (var index = 0; index < owner.Length; index++)
        {
            if (owner[index] != '`') { result.Append(owner[index]); continue; }
            index++;
            while (index < owner.Length && char.IsDigit(owner[index])) index++;
            index--;
        }
        return result.ToString();
    }

    private static bool TryWriteExecutableReference(StringBuilder source, MethodBase method, int index)
    {
        if (typeof(MulticastDelegate).IsAssignableFrom(method.DeclaringType?.BaseType)) return false;
        if (!ValidIdentifier(method.DeclaringType) || method is MethodInfo info &&
            (!ValidIdentifier(info.Name) || info.ReturnType.IsFunctionPointer)) return false;
        if (method.GetParameters().Any(parameter => parameter.ParameterType.IsFunctionPointer)) return false;

        var generics = GenericParameters(method).ToArray();
        var names = generics.Select((parameter, position) => (parameter, name: "T" + position))
            .ToDictionary(pair => pair.parameter, pair => pair.name);
        var suffix = index.ToString("D5");
        var genericDeclaration = GenericDeclaration(generics, names);
        var constraints = Constraints(generics, names);
        var parameters = method.GetParameters();
        var returnInfo = method is MethodInfo returnMethod ? SafeNullability(returnMethod.ReturnParameter) : null;
        var returnType = method is MethodInfo methodInfo
            ? ReturnType(methodInfo, names, returnInfo)
            : CSharpType(method.DeclaringType!, names);

        if (method is ConstructorInfo && method.DeclaringType!.IsAbstract)
        {
            var derived = "ContractDerived" + suffix;
            var abstractOwner = CSharpType(method.DeclaringType, names);
            var arguments = string.Join(", ", parameters.Select((parameter, position) =>
                Argument(parameter, "p" + position)));
            source.Append("    private abstract class ").Append(derived)
                .Append(genericDeclaration).Append(" : ").Append(abstractOwner).Append(constraints)
                .AppendLine();
            source.AppendLine("    {");
            source.Append("        public ").Append(derived).Append('(')
                .Append(string.Join(", ", parameters.Select((parameter, position) =>
                    ParameterDeclaration(parameter, names, position))))
                .Append(") : base(").Append(arguments).AppendLine(") { }");
            source.AppendLine("    }");
            return true;
        }

        source.Append("    private delegate ").Append(returnType).Append(" ContractDelegate")
            .Append(suffix).Append(genericDeclaration).Append('(')
            .Append(string.Join(", ", parameters.Select((parameter, position) =>
                ParameterDeclaration(parameter, names, position))))
            .Append(')').Append(constraints).AppendLine(";");
        source.Append("    private static void Reference").Append(suffix).Append(genericDeclaration)
            .Append("()").Append(constraints).AppendLine();
        source.AppendLine("    {");
        var owner = CSharpType(method.DeclaringType!, names);
        var delegateType = "ContractDelegate" + suffix + GenericUse(generics, names);
        if (method is ConstructorInfo)
        {
            var arguments = string.Join(", ", parameters.Select((parameter, position) =>
                Argument(parameter, "p" + position)));
            source.Append("        ").Append(delegateType).Append(" invocation = (")
                .Append(string.Join(", ", parameters.Select((parameter, position) =>
                    ParameterDeclaration(parameter, names, position))))
                .Append(") => new ").Append(owner).Append('(').Append(arguments).AppendLine(");");
        }
        else
        {
            var executableInfo = (MethodInfo)method;
            var target = executableInfo.IsStatic ? owner : "receiver";
            if (!executableInfo.IsStatic)
                source.Append("        ").Append(owner).AppendLine(" receiver = default!;");
            source.Append("        ").Append(delegateType).Append(" invocation = ").Append(target)
                .Append('.').Append(executableInfo.Name);
            var methodGenerics = executableInfo.GetGenericArguments().Where(item => item.DeclaringMethod is not null).ToArray();
            if (methodGenerics.Length != 0)
                source.Append('<').Append(string.Join(", ", methodGenerics.Select(item => names[item]))).Append('>');
            source.AppendLine(";");
        }
        source.AppendLine("        Consume(invocation);");
        source.AppendLine("    }");
        return true;
    }

    private static bool TryWritePropertyReference(StringBuilder source, PropertyInfo property, int index)
    {
        if (!ValidIdentifier(property.DeclaringType) || !ValidIdentifier(property.Name) ||
            property.PropertyType.IsFunctionPointer ||
            property.GetIndexParameters().Any(item => item.ParameterType.IsFunctionPointer)) return false;
        var getter = property.GetMethod;
        var setter = property.SetMethod;
        if (getter is null && setter is null) return false;

        var accessor = (MethodBase?)getter ?? setter!;
        var generics = GenericParameters(accessor).ToArray();
        var names = generics.Select((parameter, position) => (parameter, name: "T" + position))
            .ToDictionary(pair => pair.parameter, pair => pair.name);
        var suffix = index.ToString("D5");
        var genericDeclaration = GenericDeclaration(generics, names);
        var constraints = Constraints(generics, names);
        var owner = CSharpType(property.DeclaringType!, names);
        var propertyInfo = SafeNullability(property);
        var indexes = property.GetIndexParameters();

        if (getter is not null)
        {
            var returnType = CSharpType(property.PropertyType, names, propertyInfo);
            var allParameters = new List<string>();
            if (!getter.IsStatic) allParameters.Add(owner + " receiver");
            allParameters.AddRange(indexes.Select((parameter, position) =>
                ParameterDeclaration(parameter, names, position)));
            source.Append("    private delegate ").Append(returnType).Append(" PropertyDelegate")
                .Append(suffix).Append(genericDeclaration).Append('(')
                .Append(string.Join(", ", allParameters)).Append(')').Append(constraints).AppendLine(";");
            source.Append("    private static void Reference").Append(suffix).Append(genericDeclaration)
                .Append("()").Append(constraints).AppendLine();
            source.AppendLine("    {");
            source.Append("        PropertyDelegate").Append(suffix).Append(GenericUse(generics, names))
                .Append(" invocation = (").Append(string.Join(", ", allParameters.Select(ParameterName)))
                .Append(") => ");
            var target = getter.IsStatic ? owner : "receiver";
            if (indexes.Length == 0) source.Append(target).Append('.').Append(property.Name);
            else source.Append(target).Append('[')
                .Append(string.Join(", ", indexes.Select((_, position) => "p" + position))).Append(']');
            source.AppendLine(";");
            source.AppendLine("        Consume(invocation);");
            source.AppendLine("    }");
            return true;
        }

        return false;
    }

    private static bool TryWriteFieldReference(StringBuilder source, FieldInfo field, int index)
    {
        if (field.IsSpecialName || !ValidIdentifier(field.DeclaringType) || !ValidIdentifier(field.Name) ||
            field.FieldType.IsFunctionPointer) return false;
        var generics = field.DeclaringType!.GetGenericArguments().Where(item => item.IsGenericParameter).ToArray();
        var names = generics.Select((parameter, position) => (parameter, name: "T" + position))
            .ToDictionary(pair => pair.parameter, pair => pair.name);
        var suffix = index.ToString("D5");
        var genericDeclaration = GenericDeclaration(generics, names);
        var constraints = Constraints(generics, names);
        var owner = CSharpType(field.DeclaringType!, names);
        var value = CSharpType(field.FieldType, names, SafeNullability(field));
        source.Append("    private delegate ").Append(value).Append(" FieldDelegate")
            .Append(suffix).Append(genericDeclaration).Append('(');
        if (!field.IsStatic) source.Append(owner).Append(" receiver");
        source.Append(')').Append(constraints).AppendLine(";");
        source.Append("    private static void Reference").Append(suffix).Append(genericDeclaration)
            .Append("()").Append(constraints).AppendLine();
        source.AppendLine("    {");
        source.Append("        FieldDelegate").Append(suffix).Append(GenericUse(generics, names))
            .Append(" invocation = ");
        if (field.IsStatic) source.Append("() => ").Append(owner);
        else source.Append("receiver => receiver");
        source.Append('.').Append(field.Name).AppendLine(";");
        source.AppendLine("        Consume(invocation);");
        source.AppendLine("    }");
        return true;
    }

    private static string ParameterName(string declaration)
    {
        var space = declaration.LastIndexOf(' ');
        return space < 0 ? declaration : declaration[(space + 1)..];
    }

    private static string ReturnType(
        MethodInfo method,
        IReadOnlyDictionary<Type, string> names,
        NullabilityInfo? nullability)
    {
        var prefix = method.ReturnParameter.GetRequiredCustomModifiers()
            .Any(type => type.FullName == "System.Runtime.CompilerServices.IsReadOnlyAttribute")
            ? "ref readonly " : method.ReturnType.IsByRef ? "ref " : "";
        var type = method.ReturnType.IsByRef ? method.ReturnType.GetElementType()! : method.ReturnType;
        var rendered = CSharpType(type, names, nullability);
        if (type.IsGenericParameter &&
            nullability?.ReadState == System.Reflection.NullabilityState.Nullable)
            rendered += "?";
        return prefix + rendered;
    }

    private static string ParameterDeclaration(
        ParameterInfo parameter,
        IReadOnlyDictionary<Type, string> names,
        int position)
    {
        var type = parameter.ParameterType;
        var prefix = parameter.IsOut ? "out " : type.IsByRef && parameter.IsIn ? "in " :
            type.IsByRef ? "ref " : "";
        if (type.IsByRef) type = type.GetElementType()!;
        return prefix + CSharpType(type, names, SafeNullability(parameter)) + " p" + position;
    }

    private static string Argument(ParameterInfo parameter, string name) =>
        (parameter.IsOut ? "out " : parameter.ParameterType.IsByRef && parameter.IsIn ? "in " :
         parameter.ParameterType.IsByRef ? "ref " : "") + name;

    private static IEnumerable<Type> GenericParameters(MethodBase method)
    {
        foreach (var parameter in method.DeclaringType!.GetGenericArguments().Where(item => item.IsGenericParameter))
            yield return parameter;
        if (method is MethodInfo info)
            foreach (var parameter in info.GetGenericArguments().Where(item => item.IsGenericParameter))
                yield return parameter;
    }

    private static string GenericDeclaration(
        IReadOnlyCollection<Type> parameters,
        IReadOnlyDictionary<Type, string> names) => parameters.Count == 0 ? "" :
        "<" + string.Join(", ", parameters.Select(item => names[item])) + ">";

    private static string GenericUse(
        IReadOnlyCollection<Type> parameters,
        IReadOnlyDictionary<Type, string> names) => GenericDeclaration(parameters, names);

    private static string Constraints(
        IEnumerable<Type> parameters,
        IReadOnlyDictionary<Type, string> names)
    {
        var result = new StringBuilder();
        foreach (var parameter in parameters)
        {
            var values = new List<string>();
            var attributes = parameter.GenericParameterAttributes;
            var nullableAnnotation = NullableAnnotation(parameter);
            if ((attributes & GenericParameterAttributes.ReferenceTypeConstraint) != 0)
                values.Add(nullableAnnotation == 2 ? "class?" : "class");
            else if ((attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0) values.Add("struct");
            else if (nullableAnnotation == 1) values.Add("notnull");
            values.AddRange(parameter.GetGenericParameterConstraints().Select(item => CSharpType(item, names)));
            if ((attributes & GenericParameterAttributes.DefaultConstructorConstraint) != 0 &&
                (attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) == 0) values.Add("new()");
            if (values.Count != 0)
                result.Append(" where ").Append(names[parameter]).Append(" : ")
                    .Append(string.Join(", ", values));
        }
        return result.ToString();
    }

    private static byte? NullableAnnotation(Type parameter)
    {
        var direct = NullableAttributeValue(parameter.GetCustomAttributesData(), "NullableAttribute");
        if (direct is not null) return direct;
        for (MemberInfo? owner = parameter.DeclaringMethod ?? (MemberInfo?)parameter.DeclaringType;
             owner is not null;
             owner = owner is Type type ? type.DeclaringType : owner.DeclaringType)
        {
            var context = NullableAttributeValue(owner.GetCustomAttributesData(), "NullableContextAttribute");
            if (context is not null) return context;
        }
        return null;
    }

    private static byte? NullableAttributeValue(
        IEnumerable<CustomAttributeData> attributes,
        string attributeName)
    {
        var attribute = attributes.FirstOrDefault(item =>
            item.AttributeType.Namespace == "System.Runtime.CompilerServices" &&
            item.AttributeType.Name == attributeName);
        if (attribute is null || attribute.ConstructorArguments.Count != 1) return null;
        var value = attribute.ConstructorArguments[0].Value;
        if (value is byte scalar) return scalar;
        if (value is IReadOnlyCollection<CustomAttributeTypedArgument> values && values.Count != 0 &&
            values.First().Value is byte first) return first;
        return null;
    }

    private static string CSharpType(
        Type type,
        IReadOnlyDictionary<Type, string> names,
        NullabilityInfo? nullability = null,
        bool unbound = false)
    {
        if (type.IsGenericParameter)
        {
            var name = names.TryGetValue(type, out var mapped) ? mapped : type.Name;
            return name;
        }
        if (type == typeof(void)) return "void";
        if (type.IsArray)
        {
            var rank = type.GetArrayRank();
            return CSharpType(type.GetElementType()!, names, nullability?.ElementType, unbound) +
                "[" + new string(',', rank - 1) + "]" + NullableSuffix(type, nullability);
        }
        if (type.IsPointer) return CSharpType(type.GetElementType()!, names, null, unbound) + "*";
        if (type.IsByRef) return CSharpType(type.GetElementType()!, names, nullability, unbound);

        var chain = new Stack<Type>();
        for (var current = type; current is not null; current = current.DeclaringType) chain.Push(current);
        var result = new StringBuilder("global::");
        var first = true;
        var inheritedArguments = 0;
        var allArguments = type.IsGenericType ? type.GetGenericArguments() : Array.Empty<Type>();
        var nullArguments = nullability?.GenericTypeArguments ?? Array.Empty<NullabilityInfo>();
        while (chain.Count != 0)
        {
            var current = chain.Pop();
            if (first)
            {
                if (!string.IsNullOrEmpty(current.Namespace)) result.Append(current.Namespace).Append('.');
                first = false;
            }
            else result.Append('.');
            result.Append(StripArity(current.Name));
            var currentTotal = current.IsGenericType ? current.GetGenericArguments().Length : 0;
            var ownCount = Math.Max(0, currentTotal - inheritedArguments);
            if (ownCount != 0)
            {
                result.Append('<');
                if (unbound) result.Append(new string(',', ownCount - 1));
                else
                {
                    var arguments = allArguments.Skip(inheritedArguments).Take(ownCount).ToArray();
                    result.Append(string.Join(", ", arguments.Select((argument, position) =>
                        CSharpType(argument, names,
                            inheritedArguments + position < nullArguments.Length
                                ? nullArguments[inheritedArguments + position] : null,
                            unbound))));
                }
                result.Append('>');
            }
            inheritedArguments = currentTotal;
        }
        result.Append(NullableSuffix(type, nullability));
        return result.ToString();
    }

    private static string NullableSuffix(Type type, NullabilityInfo? info) =>
        !type.IsValueType && info?.ReadState == System.Reflection.NullabilityState.Nullable ? "?" : "";

    private static bool ValidIdentifier(Type? type)
    {
        for (var current = type; current is not null; current = current.DeclaringType)
            if (!ValidIdentifier(StripArity(current.Name))) return false;
        return true;
    }

    private static bool ValidIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value) || !(char.IsLetter(value[0]) || value[0] == '_')) return false;
        return value.Skip(1).All(character => char.IsLetterOrDigit(character) || character == '_') &&
            !CSharpKeywords.Contains(value);
    }

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    private static void Audit(string output, IEnumerable<Assembly> assemblies)
    {
        var candidates = new List<BodyCandidate>();
        var methodCount = 0;
        foreach (var assembly in assemblies.OrderBy(item => item.GetName().Name, StringComparer.Ordinal))
        foreach (var type in ExportedTypes(assembly).OrderBy(TypeName, StringComparer.Ordinal))
        {
            var methods = type.GetConstructors(DeclaredPublic).Cast<MethodBase>()
                .Concat(type.GetMethods(DeclaredPublic));
            foreach (var method in methods.OrderBy(MethodKey, StringComparer.Ordinal))
            {
                methodCount++;
                var finding = BodyFinding(method);
                if (finding is null) continue;
                candidates.Add(new BodyCandidate(
                    assembly.GetName().Name ?? "-", TypeName(type), method.Name,
                    MethodDisplay(method), finding));
            }
        }

        candidates.Sort((left, right) => StringComparer.Ordinal.Compare(left.Key, right.Key));
        var duplicate = candidates.GroupBy(item => item.Key, StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() != 1);
        if (duplicate is not null) throw new InvalidOperationException("Duplicate body audit row: " + duplicate.Key);
        var text = new StringBuilder("# VIBEFORMER_PUBLIC_BODY_AUDIT_V1\n");
        text.AppendLine("assembly\towner\tmember\tsignature\tfinding");
        foreach (var candidate in candidates) text.AppendLine(candidate.Tsv);
        File.WriteAllText(output, text.ToString(), new UTF8Encoding(false));
        Console.WriteLine($"Audited {methodCount} public method bodies; found {candidates.Count} review candidates.");
    }

    private static void AuditAccessible(string output, IEnumerable<Assembly> assemblies)
    {
        var rows = new List<string>();
        foreach (var assembly in assemblies.OrderBy(item => item.GetName().Name, StringComparer.Ordinal))
        foreach (var type in AccessibleTypes(assembly).OrderBy(TypeName, StringComparer.Ordinal))
        {
            var methods = type.GetConstructors(DeclaredAccessible).Cast<MethodBase>()
                .Concat(type.GetMethods(DeclaredAccessible))
                .Where(IsExternallyAccessible);
            foreach (var method in methods.OrderBy(MethodKey, StringComparer.Ordinal))
            {
                var finding = BodyFinding(method) ?? (method.IsAbstract ? "abstract-contract" : "implemented");
                rows.Add(string.Join('\t', new[]
                {
                    Clean(assembly.GetName().Name ?? "-"), Clean(TypeName(type)), Clean(method.Name),
                    method.GetParameters().Length.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    Clean(MethodDisplay(method)), finding
                }));
            }
        }

        rows.Sort(StringComparer.Ordinal);
        if (rows.Count != rows.Distinct(StringComparer.Ordinal).Count())
            throw new InvalidOperationException("Accessible body audit produced duplicate rows.");
        var text = new StringBuilder("# VIBEFORMER_ACCESSIBLE_BODY_AUDIT_V1\n");
        text.AppendLine("assembly\towner\tmember\tparameter-count\tsignature\tfinding");
        foreach (var row in rows) text.AppendLine(row);
        File.WriteAllText(output, text.ToString(), new UTF8Encoding(false));
        Console.WriteLine($"Audited {rows.Count} public/protected method bodies.");
    }

    private static bool IsExternallyAccessible(MethodBase method) =>
        method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;

    private static bool IsExternallyVisible(Type type)
    {
        if (!(type.IsPublic || type.IsNestedPublic || type.IsNestedFamily || type.IsNestedFamORAssem))
            return false;
        return type.DeclaringType is null || IsExternallyVisible(type.DeclaringType);
    }

    private static IEnumerable<Type> AccessibleTypes(Assembly assembly) =>
        AllTypes(assembly).Where(IsExternallyVisible);

    private static string? BodyFinding(MethodBase method)
    {
        if (method.IsAbstract ||
            typeof(MulticastDelegate).IsAssignableFrom(method.DeclaringType?.BaseType)) return null;
        var body = method.GetMethodBody();
        if (body is null) return "concrete-body-unreachable";
        var bytes = body.GetILAsByteArray() ?? Array.Empty<byte>();
        var instructions = Decode(method, bytes).Where(item => item.OpCode != OpCodes.Nop).ToArray();
        if (instructions.Length == 1 && instructions[0].OpCode == OpCodes.Ret && method is MethodInfo)
            return "empty-no-op";
        if (instructions.Length == 2 && instructions[1].OpCode == OpCodes.Ret)
        {
            if (instructions[0].OpCode == OpCodes.Ldnull) return "constant-null";
            if (instructions[0].OpCode == OpCodes.Ldc_I4_0) return "constant-zero";
        }
        if (instructions.Length <= 5 && instructions[^1].OpCode == OpCodes.Ret &&
            instructions.Any(item => item.OpCode == OpCodes.Initobj)) return "constant-default";
        if (instructions.Length <= 4 && instructions[^1].OpCode == OpCodes.Ret &&
            instructions.Any(item => item.Member is MethodInfo info && info.DeclaringType == typeof(Array) &&
                info.Name == nameof(Array.Empty))) return "constant-empty";
        if (instructions.Length <= 4 && instructions[^1].OpCode == OpCodes.Throw)
        {
            var exception = instructions.Select(item => item.Member).OfType<ConstructorInfo>()
                .Select(item => item.DeclaringType).FirstOrDefault(item => item is not null);
            if (exception == typeof(NotImplementedException)) return "unconditional-not-implemented";
            if (exception == typeof(NotSupportedException)) return "unconditional-unsupported";
        }
        return null;
    }

    private sealed record Instruction(OpCode OpCode, MemberInfo? Member);

    private static IEnumerable<Instruction> Decode(MethodBase method, byte[] bytes)
    {
        var index = 0;
        while (index < bytes.Length)
        {
            short value = bytes[index++];
            if (value == 0xfe) value = (short)(0xfe00 | bytes[index++]);
            if (!OpCodesByValue.TryGetValue(value, out var opCode))
                throw new InvalidDataException($"Unknown IL opcode 0x{value:x} in {method}.");
            MemberInfo? member = null;
            var size = OperandSize(opCode.OperandType, bytes, index);
            if (opCode.OperandType is OperandType.InlineField or OperandType.InlineMethod or
                OperandType.InlineTok or OperandType.InlineType)
            {
                var token = BitConverter.ToInt32(bytes, index);
                try
                {
                    member = method.Module.ResolveMember(token,
                        method.DeclaringType?.GetGenericArguments(),
                        method is MethodInfo info ? info.GetGenericArguments() : null);
                }
                catch (Exception error) when (error is ArgumentException or BadImageFormatException) { }
            }
            index += size;
            yield return new Instruction(opCode, member);
        }
    }

    private static int OperandSize(OperandType type, byte[] bytes, int index) => type switch
    {
        OperandType.InlineNone => 0,
        OperandType.ShortInlineBrTarget or OperandType.ShortInlineI or OperandType.ShortInlineVar => 1,
        OperandType.InlineVar => 2,
        OperandType.InlineBrTarget or OperandType.InlineField or OperandType.InlineI or
            OperandType.InlineMethod or OperandType.InlineSig or OperandType.InlineString or
            OperandType.InlineTok or OperandType.InlineType or OperandType.ShortInlineR => 4,
        OperandType.InlineI8 or OperandType.InlineR => 8,
        OperandType.InlineSwitch => 4 + BitConverter.ToInt32(bytes, index) * 4,
        _ => throw new InvalidDataException("Unsupported IL operand type: " + type)
    };

    private static Dictionary<short, OpCode> BuildOpCodes() => typeof(OpCodes)
        .GetFields(BindingFlags.Public | BindingFlags.Static)
        .Where(field => field.FieldType == typeof(OpCode))
        .Select(field => (OpCode)field.GetValue(null)!)
        .ToDictionary(opCode => opCode.Value);

    private static string Row(Type type) => string.Join('|',
        type.Assembly.GetName().Name, TypeName(type), "type", TypeDisplay(type));

    private static string Row(MethodBase method) => string.Join('|',
        method.DeclaringType!.Assembly.GetName().Name, TypeName(method.DeclaringType),
        method is ConstructorInfo ? "constructor" : "method", MethodDisplay(method),
        ExecutableNullability(method));

    private static string Row(PropertyInfo property) => string.Join('|',
        property.DeclaringType!.Assembly.GetName().Name, TypeName(property.DeclaringType),
        "property", property.Name, TypeDisplay(property.PropertyType),
        NullabilityState(() => Nullability.Create(property)));

    private static string Row(FieldInfo field) => string.Join('|',
        field.DeclaringType!.Assembly.GetName().Name, TypeName(field.DeclaringType),
        field.IsLiteral && field.DeclaringType.IsEnum ? "enum-value" : "field", field.Name,
        TypeDisplay(field.FieldType), NullabilityState(() => Nullability.Create(field)));

    private static string ExecutableNullability(MethodBase method)
    {
        var values = new List<string>();
        if (method is MethodInfo info)
            values.Add("return=" + NullabilityState(() => Nullability.Create(info.ReturnParameter)));
        values.AddRange(method.GetParameters().Select((parameter, index) =>
            "param" + index + "=" + NullabilityState(() => Nullability.Create(parameter))));
        return string.Join(';', values);
    }

    private static string MethodDisplay(MethodBase method)
    {
        var result = new StringBuilder();
        if (method is MethodInfo info)
        {
            if (info.IsGenericMethodDefinition)
                result.Append('<').Append(string.Join(',', info.GetGenericArguments().Select(item => item.Name)))
                    .Append("> ");
            result.Append(TypeDisplay(info.ReturnType)).Append(' ');
        }
        result.Append(method is ConstructorInfo ? ".ctor" : method.Name).Append('(')
            .Append(string.Join(',', method.GetParameters().Select(parameter =>
                (parameter.IsOut ? "out " : parameter.ParameterType.IsByRef ? "ref " : "") +
                TypeDisplay(parameter.ParameterType.IsByRef
                    ? parameter.ParameterType.GetElementType()! : parameter.ParameterType))))
            .Append(')');
        return result.ToString();
    }

    private static string MethodKey(MethodBase method) => MethodDisplay(method);

    private static string TypeDisplay(Type type)
    {
        if (type.IsGenericParameter) return type.Name;
        if (type.IsArray) return TypeDisplay(type.GetElementType()!) + "[" +
            new string(',', type.GetArrayRank() - 1) + "]";
        if (type.IsPointer) return TypeDisplay(type.GetElementType()!) + "*";
        if (type.IsByRef) return TypeDisplay(type.GetElementType()!) + "&";
        if (!type.IsGenericType) return TypeName(type);
        var definition = type.GetGenericTypeDefinition();
        var name = TypeName(definition);
        var tick = name.IndexOf('`', StringComparison.Ordinal);
        if (tick >= 0) name = name[..tick];
        return name + "<" + string.Join(',', type.GetGenericArguments().Select(TypeDisplay)) + ">";
    }

    private static NullabilityInfo? SafeNullability(ParameterInfo parameter)
    {
        try { return Nullability.Create(parameter); }
        catch (Exception error) when (error is InvalidOperationException or ArgumentException or NotSupportedException)
        { return null; }
    }

    private static NullabilityInfo? SafeNullability(PropertyInfo property)
    {
        try { return Nullability.Create(property); }
        catch (Exception error) when (error is InvalidOperationException or ArgumentException or NotSupportedException)
        { return null; }
    }

    private static NullabilityInfo? SafeNullability(FieldInfo field)
    {
        try { return Nullability.Create(field); }
        catch (Exception error) when (error is InvalidOperationException or ArgumentException or NotSupportedException)
        { return null; }
    }

    private static string NullabilityState(Func<NullabilityInfo> read)
    {
        try { return read().ReadState.ToString(); }
        catch (Exception error) when (error is InvalidOperationException or ArgumentException or NotSupportedException)
        { return "Unknown"; }
    }

    private static IEnumerable<Type> ExportedTypes(Assembly assembly)
    {
        try { return assembly.GetExportedTypes(); }
        catch (ReflectionTypeLoadException error)
        {
            var loaderErrors = string.Join(" | ", error.LoaderExceptions.Where(item => item is not null)
                .Select(item => item!.GetType().Name + ": " + item.Message));
            throw new InvalidOperationException("Could not load every public package type: " + loaderErrors, error);
        }
    }

    private static IEnumerable<Type> AllTypes(Assembly assembly)
    {
        try { return assembly.GetTypes(); }
        catch (ReflectionTypeLoadException error)
        {
            var loaderErrors = string.Join(" | ", error.LoaderExceptions.Where(item => item is not null)
                .Select(item => item!.GetType().Name + ": " + item.Message));
            throw new InvalidOperationException("Could not load every package type: " + loaderErrors, error);
        }
    }

    private static string TypeName(Type type) => (type.FullName ?? type.Name).Replace('+', '$');
    private static string StripArity(string value)
    {
        var tick = value.IndexOf('`', StringComparison.Ordinal);
        return tick < 0 ? value : value[..tick];
    }
    private static string Sha256(string path) =>
        Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();
    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal);
    private static string Clean(string value) => value.Replace("\t", "\\t", StringComparison.Ordinal)
        .Replace("\r", " ", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
}
