(ns vibeformer.datomic.schema
  (:require [datomic.client.api :as d]))

(def project
  [{:db/ident :project/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :project/name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :project/root
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}])

(def file
  [{:db/ident :file/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :file/path
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :file/lang
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :file/hash
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :file/project
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :file/package
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}])

(def node
  [{:db/ident :node/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :node/lang
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/kind
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/file
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/parent
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/ordinal
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/start-line
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/start-column
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/end-line
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/end-column
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :node/source-hash
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}])

(def declaration
  [{:db/ident :decl/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :decl/lang
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/kind
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/qualified-name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/source-node
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/return-type
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/type
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :decl/modifiers
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/many}])

(def source-type
  [{:db/ident :type/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :type/lang
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :type/name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :type/nullable?
    :db/valueType :db.type/boolean
    :db/cardinality :db.cardinality/one}
   {:db/ident :type/args
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/many
    :db/isComponent true}
   {:db/ident :type.arg/ordinal
    :db/valueType :db.type/long
    :db/cardinality :db.cardinality/one}
   {:db/ident :type.arg/type
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}])

(def reference
  [{:db/ident :ref/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :ref/kind
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/from-node
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/to-decl
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/to-type
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/name
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/owner-type
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/resolved?
    :db/valueType :db.type/boolean
    :db/cardinality :db.cardinality/one}
   {:db/ident :ref/reason
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}])

(def feature
  [{:db/ident :feature/id
    :db/valueType :db.type/string
    :db/cardinality :db.cardinality/one
    :db/unique :db.unique/identity}
   {:db/ident :feature/lang
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :feature/kind
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :feature/node
    :db/valueType :db.type/ref
    :db/cardinality :db.cardinality/one}
   {:db/ident :feature/status
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}
   {:db/ident :feature/severity
    :db/valueType :db.type/keyword
    :db/cardinality :db.cardinality/one}])

(def all
  (vec (concat project file node declaration source-type reference feature)))

(def schema all)

(defn install! [conn]
  (d/transact conn {:tx-data all}))
